name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.target }}

      - name: Install dependencies
        run: sudo apt-get install gcc-multilib gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/shpool
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/shpool
            target/x86_64-unknown-linux-musl/release/shpool
            target/i686-unknown-linux-gnu/release/shpool
            target/i686-unknown-linux-musl/release/shpool
            target/armv7-unknown-linux-gnueabihf/release/shpool
            target/armv7-unknown-linux-musleabihf/release/shpool
            target/aarch64-unknown-linux-gnu/release/shpool
            target/aarch64-unknown-linux-musl/release/shpool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
