name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when a new version tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build the binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload release asset
        uses: actions/upload-artifact@v3
        with:
          name: shpool-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/shpool

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: shpool-x86_64-unknown-linux-gnu

      - name: Download musl binaries
        uses: actions/download-artifact@v3
        with:
          name: shpool-x86_64-unknown-linux-musl

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/shpool
            target/x86_64-unknown-linux-musl/release/shpool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
