name: Build and Release aarch64

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when a new version tag is pushed
  workflow_dispatch:  # Allows manual execution of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install cross for cross-compilation
        run: cargo install cross

      - name: Build with cross for aarch64-unknown-linux-gnu
        run: |
          cross build --release --target aarch64-unknown-linux-gnu

      - name: Build with cross for aarch64-unknown-linux-musl
        run: |
          cross build --release --target aarch64-unknown-linux-musl

      - name: Rename the GNU binary
        run: mv target/aarch64-unknown-linux-gnu/release/shpool target/aarch64-unknown-linux-gnu/release/shpool-aarch64-unknown-linux-gnu

      - name: Rename the musl binary
        run: mv target/aarch64-unknown-linux-musl/release/shpool target/aarch64-unknown-linux-musl/release/shpool-aarch64-unknown-linux-musl

      - name: Upload release asset
        uses: actions/upload-artifact@v3
        with:
          name: shpool-${{ matrix.target }}
          path: |
            target/aarch64-unknown-linux-gnu/release/shpool-aarch64-unknown-linux-gnu
            target/aarch64-unknown-linux-musl/release/shpool-aarch64-unknown-linux-musl

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: shpool-aarch64-unknown-linux-gnu
          path: download/aarch64-unknown-linux-gnu

      - name: Download musl binaries
        uses: actions/download-artifact@v3
        with:
          name: shpool-aarch64-unknown-linux-musl
          path: download/aarch64-unknown-linux-musl

      - name: List downloaded files
        run: ls -R download

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            download/aarch64-unknown-linux-gnu/shpool-aarch64-unknown-linux-gnu
            download/aarch64-unknown-linux-musl/shpool-aarch64-unknown-linux-musl
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
